### PR TITLE
Add text selection to knot feature

### PR DESCRIPTION
**Pull request by spencerjsmall**

### CODE REVIEW

**Comment by joelrojo** [comment]
This looks dope, but what's the UX look like here? Seems like you highlight then it creates a Knot. 

Can you drop a quick Loom video [signup here](https://www.loom.com/) or gif of the UX you ended up going with?

**Comment by spencerjsmall** [comment]
Here's a quick vid of the UX! Using the keyboard shortcut to activate the extension, although clicking it works as well for this feature: https://www.loom.com/share/ede0d44d3f3f464dadf8271128f9d6de

**Comment by joelrojo** [comment]
> Here's a quick vid of the UX! Using the keyboard shortcut to activate the extension, although clicking it works as well for this feature: https://www.loom.com/share/ede0d44d3f3f464dadf8271128f9d6de

Sickkk. Love that. Does it allow for multiple notes or only on the first create? Ideally would be able to keep hitting the shortcut and if it's already opened and logged then it just adds a new note.

Also wondering if we should add it to the [ContextMenu](https://developer.chrome.com/extensions/contextMenus) as well (when you right click after highlight, then it says something like "Add as a note")

**Comment by spencerjsmall** [comment]
Yes I totally agree! Might need help with that but i'll give it a shot today.

**Comment by joelrojo** [comment]
> Yes I totally agree! Might need help with that but i'll give it a shot today.

For sure, I think I already use the contextMenu to "add to analogue" basically as a shortcut to activate the main action (logging the page). But looks like you can use the built in ContextMenu API to also get the selectedText:

https://developer.chrome.com/apps/contextMenus (See the `onClick` section and `selectedText` object at the bottom) 

There's probably a way to also show a different contextMenu if you have text selected vs just a regular right click

**Comment by spencerjsmall** [comment]
https://www.loom.com/share/bf7fa93f213a447e99b514285ad1dffa fully functioning!

**Comment by joelrojo** [comment]
> https://www.loom.com/share/bf7fa93f213a447e99b514285ad1dffa fully functioning!

So sickkkkk! Going to use this feature soooo much, hell yea man!!

**Pull request merged**
